# Generated by Django 3.1.1 on 2021-01-28 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('department_type', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=userprofile.models.user_image_path)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('middle_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('skill_level', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('alternate_email_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('personal_phone_number', models.CharField(max_length=50)),
                ('altername_phone_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('passpart_number', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=300)),
                ('mother_name', models.CharField(max_length=300)),
                ('marital_status', models.CharField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Widowed'), (4, 'Divorced'), (5, 'Engaged')], max_length=300)),
                ('spouse_name', models.CharField(max_length=300)),
                ('emergency_contact_number_1', models.CharField(max_length=40)),
                ('emergency_contact_number_2', models.CharField(max_length=40)),
                ('project_assigned', models.CharField(max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='userprofile.department', verbose_name='emp_department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
