# Generated by Django 3.1.1 on 2021-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210128_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE'), ('3', 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Widowed'), ('4', 'Divorced'), ('5', 'Engaged')], max_length=300, null=True),
        ),
    ]
