# Generated by Django 3.1.1 on 2021-01-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210129_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='altername_phone_number',
            new_name='alternate_phone_number',
        ),
    ]
