# Generated by Django 3.1.1 on 2021-01-31 17:12

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210129_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=userprofile.models.user_image_path),
        ),
    ]
